export const BATCH_CONFIG = {
  DEFAULT_CONCURRENCY: 3,
  DEFAULT_BATCH_SIZE: 10,
  CHUNK_SIZE_USERS: 100,
  CHUNK_SIZE_PROJECTS: 100,
  CHUNK_SIZE_TASKS: 100,
  CHUNK_SIZE_SUBTASKS: 50,
  CHUNK_SIZE_STATS: 50,
} as const;

export const CACHE_CONFIG = {
  TTL_MS: 5 * 60 * 1000,
} as const;
